In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
 print(plt.style.available)

['Solarize_Light2', '_classic_test_patch', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark', 'seaborn-dark-palette', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'tableau-colorblind10']

In [3]:
train_data = pd.read_csv("Train_data")

In [4]:
train_data.head()

  a1 a2 a3 a4 a5 a6 b1 b2 b3 b4  ... f4 f5 f6 g1 g2 g3 g4 g5 g6 class
0  b  b  b  b  b  b  o  o  x  b  ...  b  b  b  b  b  b  b  b  b  loss
1  b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b  loss
2  x  x  o  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
3  x  x  b  b  b  b  o  b  b  b  ...  b  b  b  o  x  o  x  b  b   win
4  x  x  o  o  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b   win

[5 rows x 43 columns]

In [5]:
train_data.isnull().sum()

a1       0
a2       0
a3       0
a4       0
a5       0
a6       0
b1       0
b2       0
b3       0
b4       0
b5       0
b6       0
c1       0
c2       0
c3       0
c4       0
c5       0
c6       0
d1       0
d2       0
d3       0
d4       0
d5       0
d6       0
e1       0
e2       0
e3       0
e4       0
e5       0
e6       0
f1       0
f2       0
f3       0
f4       0
f5       0
f6       0
g1       0
g2       0
g3       0
g4       0
g5       0
g6       0
class    0
dtype: int64

In [6]:
train_data.shape

(50667, 43)

In [7]:
train_data.dtypes

a1       object
a2       object
a3       object
a4       object
a5       object
a6       object
b1       object
b2       object
b3       object
b4       object
b5       object
b6       object
c1       object
c2       object
c3       object
c4       object
c5       object
c6       object
d1       object
d2       object
d3       object
d4       object
d5       object
d6       object
e1       object
e2       object
e3       object
e4       object
e5       object
e6       object
f1       object
f2       object
f3       object
f4       object
f5       object
f6       object
g1       object
g2       object
g3       object
g4       object
g5       object
g6       object
class    object
dtype: object

In [8]:
for cols in train_data:
    print(f'{cols}:{train_data[cols].unique()}')

a1:['b' 'x' 'o']
a2:['b' 'x' 'o']
a3:['b' 'o' 'x']
a4:['b' 'o' 'x']
a5:['b' 'o' 'x']
a6:['b' 'o' 'x']
b1:['o' 'b' 'x']
b2:['o' 'b' 'x']
b3:['x' 'b' 'o']
b4:['b' 'o' 'x']
b5:['b' 'o' 'x']
b6:['b' 'x' 'o']
c1:['x' 'b' 'o']
c2:['x' 'o' 'b']
c3:['o' 'b' 'x']
c4:['x' 'b' 'o']
c5:['b' 'x' 'o']
c6:['b' 'o' 'x']
d1:['b' 'x' 'o']
d2:['b' 'x' 'o']
d3:['b' 'x' 'o']
d4:['b' 'o' 'x']
d5:['b' 'x' 'o']
d6:['b' 'o' 'x']
e1:['o' 'x' 'b']
e2:['b' 'x' 'o']
e3:['b' 'o' 'x']
e4:['b' 'o' 'x']
e5:['b' 'o' 'x']
e6:['b' 'o' 'x']
f1:['b' 'o' 'x']
f2:['b' 'x' 'o']
f3:['b' 'x' 'o']
f4:['b' 'o' 'x']
f5:['b' 'o' 'x']
f6:['b' 'x' 'o']
g1:['b' 'o' 'x']
g2:['b' 'x' 'o']
g3:['b' 'o' 'x']
g4:['b' 'x' 'o']
g5:['b' 'x' 'o']
g6:['b' 'o' 'x']
class:['loss' 'win' 'draw']

In [9]:
train_data.shape

(50667, 43)

In [10]:
get_dum = train_data.iloc[:,:-1]

In [11]:
get_dum

      a1 a2 a3 a4 a5 a6 b1 b2 b3 b4  ... f3 f4 f5 f6 g1 g2 g3 g4 g5 g6
0      b  b  b  b  b  b  o  o  x  b  ...  b  b  b  b  b  b  b  b  b  b
1      b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
2      x  x  o  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
3      x  x  b  b  b  b  o  b  b  b  ...  b  b  b  b  o  x  o  x  b  b
4      x  x  o  o  b  b  o  b  b  b  ...  x  b  b  b  b  b  b  b  b  b
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
50662  x  o  o  b  b  b  b  b  b  b  ...  b  b  b  b  x  o  b  b  b  b
50663  x  b  b  b  b  b  o  x  o  o  ...  b  b  b  b  x  b  b  b  b  b
50664  x  x  o  o  b  b  o  x  x  o  ...  b  b  b  b  b  b  b  b  b  b
50665  o  o  x  o  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
50666  o  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b  b

[50667 rows x 42 columns]

In [12]:
dependent_var = train_data.iloc[:,-1]
dependent_var

0        loss
1        loss
2         win
3         win
4         win
         ...
50662     win
50663     win
50664    loss
50665     win
50666     win
Name: class, Length: 50667, dtype: object

In [13]:
df = pd.get_dummies(get_dum)

In [14]:
df

,a1_b,a1_o,a1_x,a2_b,a2_o,a2_x,a3_b,a3_o,a3_x,a4_b,...,g3_x,g4_b,g4_o,g4_x,g5_b,g5_o,g5_x,g6_b,g6_o,g6_x
0,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
1,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
2,0,0,1,0,0,1,0,1,0,1,...,0,1,0,0,1,0,0,1,0,0
3,0,0,1,0,0,1,1,0,0,1,...,0,0,0,1,1,0,0,1,0,0
4,0,0,1,0,0,1,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50662,0,0,1,0,1,0,0,1,0,1,...,0,1,0,0,1,0,0,1,0,0
50663,0,0,1,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
50664,0,0,1,0,0,1,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0
50665,0,1,0,0,1,0,0,0,1,0,...,0,1,0,0,1,0,0,1,0,0
50666,0,1,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0

In [15]:
dependent_var.replace('win',1,inplace=True)
dependent_var.replace('loss',0,inplace=True)

In [16]:
dependent_var = pd.DataFrame(dependent_var)
dependent_var

      class
0         0
1         0
2         1
3         1
4         1
...     ...
50662     1
50663     1
50664     0
50665     1
50666     1

[50667 rows x 1 columns]

In [17]:
df = df.append(dependent_var, ignore_index=True)

In [18]:
df

,a1_b,a1_o,a1_x,a2_b,a2_o,a2_x,a3_b,a3_o,a3_x,a4_b,...,g4_b,g4_o,g4_x,g5_b,g5_o,g5_x,g6_b,g6_o,g6_x,class
0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
2,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
3,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
101330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
101331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
101332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
101333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [19]:
df['class'].unique()

array([nan, 0, 1, 'draw'], dtype=object)

### Preprocessing

In [20]:
df = train_data.copy()

In [21]:
df

      a1 a2 a3 a4 a5 a6 b1 b2 b3 b4  ... f4 f5 f6 g1 g2 g3 g4 g5 g6 class
0      b  b  b  b  b  b  o  o  x  b  ...  b  b  b  b  b  b  b  b  b     0
1      b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b     0
2      x  x  o  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b     1
3      x  x  b  b  b  b  o  b  b  b  ...  b  b  b  o  x  o  x  b  b     1
4      x  x  o  o  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b     1
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. ..   ...
50662  x  o  o  b  b  b  b  b  b  b  ...  b  b  b  x  o  b  b  b  b     1
50663  x  b  b  b  b  b  o  x  o  o  ...  b  b  b  x  b  b  b  b  b     1
50664  x  x  o  o  b  b  o  x  x  o  ...  b  b  b  b  b  b  b  b  b     0
50665  o  o  x  o  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b     1
50666  o  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b     1

[50667 rows x 43 columns]

In [22]:
dummies = pd.get_dummies(df.iloc[:,:-1])

In [23]:
dummies

,a1_b,a1_o,a1_x,a2_b,a2_o,a2_x,a3_b,a3_o,a3_x,a4_b,...,g3_x,g4_b,g4_o,g4_x,g5_b,g5_o,g5_x,g6_b,g6_o,g6_x
0,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
1,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
2,0,0,1,0,0,1,0,1,0,1,...,0,1,0,0,1,0,0,1,0,0
3,0,0,1,0,0,1,1,0,0,1,...,0,0,0,1,1,0,0,1,0,0
4,0,0,1,0,0,1,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50662,0,0,1,0,1,0,0,1,0,1,...,0,1,0,0,1,0,0,1,0,0
50663,0,0,1,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
50664,0,0,1,0,0,1,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0
50665,0,1,0,0,1,0,0,0,1,0,...,0,1,0,0,1,0,0,1,0,0
50666,0,1,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0

In [24]:
df

      a1 a2 a3 a4 a5 a6 b1 b2 b3 b4  ... f4 f5 f6 g1 g2 g3 g4 g5 g6 class
0      b  b  b  b  b  b  o  o  x  b  ...  b  b  b  b  b  b  b  b  b     0
1      b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b     0
2      x  x  o  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b     1
3      x  x  b  b  b  b  o  b  b  b  ...  b  b  b  o  x  o  x  b  b     1
4      x  x  o  o  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b     1
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. ..   ...
50662  x  o  o  b  b  b  b  b  b  b  ...  b  b  b  x  o  b  b  b  b     1
50663  x  b  b  b  b  b  o  x  o  o  ...  b  b  b  x  b  b  b  b  b     1
50664  x  x  o  o  b  b  o  x  x  o  ...  b  b  b  b  b  b  b  b  b     0
50665  o  o  x  o  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b     1
50666  o  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b     1

[50667 rows x 43 columns]

In [35]:
df = pd.concat([dummies, df['class']],axis=1)

In [36]:
df

,a1_b,a1_o,a1_x,a2_b,a2_o,a2_x,a3_b,a3_o,a3_x,a4_b,...,g4_b,g4_o,g4_x,g5_b,g5_o,g5_x,g6_b,g6_o,g6_x,class
0,1,0,0,1,0,0,1,0,0,1,...,1,0,0,1,0,0,1,0,0,0
1,1,0,0,1,0,0,1,0,0,1,...,1,0,0,1,0,0,1,0,0,0
2,0,0,1,0,0,1,0,1,0,1,...,1,0,0,1,0,0,1,0,0,1
3,0,0,1,0,0,1,1,0,0,1,...,0,0,1,1,0,0,1,0,0,1
4,0,0,1,0,0,1,0,1,0,0,...,1,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50662,0,0,1,0,1,0,0,1,0,1,...,1,0,0,1,0,0,1,0,0,1
50663,0,0,1,1,0,0,1,0,0,1,...,1,0,0,1,0,0,1,0,0,1
50664,0,0,1,0,0,1,0,1,0,0,...,1,0,0,1,0,0,1,0,0,0
50665,0,1,0,0,1,0,0,0,1,0,...,1,0,0,1,0,0,1,0,0,1
50666,0,1,0,1,0,0,1,0,0,1,...,1,0,0,1,0,0,1,0,0,1

### Model Building

In [26]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [27]:
# X = np.asarray(X).astype(np.float32)

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten,Dense

In [30]:
model = Sequential()

In [34]:
model.add(Flatten(input_shape=(127,)))
model.add(Dense(128,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [35]:
# model = keras.Sequential([
#     keras.layers.Dense(20,input_shape=(126,),activation='relu'),
#     keras.layers.Dense(15,activation='relu'),
#     keras.layers.Dense(3,activation='softmax'),
# ])
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [36]:
history = model.fit(X_train,y_train,epochs=100,batch_size=10,validation_split=0.2)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).